MOVED_LEFT = 'MOVED_LEFT'
MOVED_RIGHT = 'MOVED_RIGHT'
MOVED_UP = 'MOVED_UP'
MOVED_DOWN = 'MOVED_DOWN'
WAITED = 'WAITED'
INVALID_ACTION = 'INVALID_ACTION'

BOMB_DROPPED = 'BOMB_DROPPED'
BOMB_EXPLODED = 'BOMB_EXPLODED'

CRATE_DESTROYED = 'CRATE_DESTROYED'
COIN_FOUND = 'COIN_FOUND'
COIN_COLLECTED = 'COIN_COLLECTED'

KILLED_OPPONENT = 'KILLED_OPPONENT'
KILLED_SELF = 'KILLED_SELF'

GOT_KILLED = 'GOT_KILLED'
OPPONENT_ELIMINATED = 'OPPONENT_ELIMINATED'
SURVIVED_ROUND = 'SURVIVED_ROUND'

MOVED_TOWARDS_COIN = 'MOVED_TOWARDS_COIN'
MOVED_AWAY_FROM_COIN = 'MOVED_AWAY_FROM_COIN'

MOVED_TOWARDS_COIN1 = 'MOVED_TOWARDS_COIN1'
MOVED_AWAY_FROM_COIN1 = 'MOVED_AWAY_FROM_COIN1'
MOVED_TOWARDS_COIN2 = 'MOVED_TOWARDS_COIN2'
MOVED_AWAY_FROM_COIN2 = 'MOVED_AWAY_FROM_COIN2'